application: color-flow
version: 3
runtime: python27
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images

- url: .*
  script: main.py

builtins:
- datastore_admin: on
